### PR TITLE
update to TF2, uproot4, etc.

### PR DESCRIPTION
**Pull request by jmduarte**
@ExcitingSquid @yongbinfeng I'm trying to update the code to TF2, uproot4, etc. and make a clean environment for people to start from.

Still kind of a work in progress, but let me know what you think.

Also, we should try to centralize developments for L1 MET training + hls4ml conversion into 1 repo. I'm fine if it's this one or Yongbin's (https://github.com/yongbinfeng/DeepMETTraining/tree/l1met), but we should have a main repo that everyone can start from without getting too confused.

### CODE REVIEW

**Comment by yongbinfeng** [comment]
i'm slightly in favor of centralizing code here since this repo has been under development for some time and contains most of the information. i can help check the deepmet model.

**Comment by jmduarte** [comment]
Great sounds good! Yeah, I fixed a small difference I saw between your repo and this one in 3c30c252572e648e121f121b0e71e2e497c52366. I also added a script (0553ea06ea8a0788f4bea6bce464c00b48dc7718) to split up the model for tests deploying it using hls4ml.

**Comment by jmduarte** [comment]
@ExcitingSquid can you test out this branch and see if it works for you? 

Does this include all the latest developments? 

If so we can push this to master and start using this branch as the default.

For @Raynchowkw @JingminZhao, you can start from this branch `DeepMet_merge_tf2` and if you make any new contributions you can either commit it to a new branch or your fork of this repo... and then we'll make pull requests to `master`.

Does that make sense?

**Comment by Raynchowkw** [comment]
Is there a place to ask some general questions like environment set up problem? I think this conversion for pull request is not a good place.

**Comment by ExcitingSquid** [comment]
Sorry for the late update @jmduarte, I just tested and found some errors.
1. somewhat reason,  `matplotlib.pyplot.pause` made some problem. So I just commented out.
[https://github.com/jmduarte/L1METML/commit/e738861ce2284a0e54e919a5f1ea5d38b0428556](url)

2. in the DeepMET model, the output data has a dimension with (?,4) which is not equals to the target dimension (?,2). So I added one more layer to make the output dimension from (?,4) to (?,2).
[https://github.com/jmduarte/L1METML/commit/87b757aef80c534929a381c75afefbc43cc98171](url)

**Pull request merged**
